#!/usr/bin/env bash
# Pagayo — decision thread scope guard (THREAD-ENFORCEMENT.md)
# Gebruik: decision-thread-preflight.sh [repo-path]
#        decision-thread-preflight.sh --init --thread ID --slug SLUG [--repos a,b] [--excludes x]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_PATH="."
INIT_MODE=0
THREAD_ID=""
SLUG=""
REPOS=""
EXCLUDES=""

usage() {
  cat <<'EOF'
Gebruik:
  decision-thread-preflight.sh [repo-path]
  decision-thread-preflight.sh --init --thread <id> --slug <slug> [--repos a,b] [--excludes x,y]

Exit codes: 0 OK/WARN, 1 FAIL (cross-thread of branch/manifest conflict)
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --init)
      INIT_MODE=1
      shift
      ;;
    --thread)
      THREAD_ID="${2:-}"
      shift 2
      ;;
    --slug)
      SLUG="${2:-}"
      shift 2
      ;;
    --repos)
      REPOS="${2:-}"
      shift 2
      ;;
    --excludes)
      EXCLUDES="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      REPO_PATH="$1"
      shift
      ;;
  esac
done

WS="$(cd "$SCRIPT_DIR/../../.." && pwd)"
MANIFEST_DIR="$WS/.pagayo"
MANIFEST_FILE="$MANIFEST_DIR/decision-thread.json"

init_manifest() {
  if [[ -z "$THREAD_ID" || -z "$SLUG" ]]; then
    echo "❌ --init vereist --thread en --slug"
    exit 1
  fi
  mkdir -p "$MANIFEST_DIR"
  local repos_json excludes_json branch_hint
  if [[ -n "$REPOS" ]]; then
    repos_json="$(printf '%s' "$REPOS" | awk -F, '{printf "["; for(i=1;i<=NF;i++){gsub(/^ +| +$/,"",$i); printf "%s\"%s\"", (i>1?",":""), $i} printf "]"}')"
  else
    repos_json='["pagayo-storefront"]'
  fi
  if [[ -n "$EXCLUDES" ]]; then
    excludes_json="$(printf '%s' "$EXCLUDES" | awk -F, '{printf "["; for(i=1;i<=NF;i++){gsub(/^ +| +$/,"",$i); printf "%s\"%s\"", (i>1?",":""), $i} printf "]"}')"
  else
    excludes_json='[]'
  fi
  branch_hint="feature/batch-staging-$(date +%Y%m%d)-${SLUG}"
  cat >"$MANIFEST_FILE" <<EOF
{
  "version": 1,
  "thread_id": "$THREAD_ID",
  "slug": "$SLUG",
  "excludes": $excludes_json,
  "repos": $repos_json,
  "created": "$(date +%Y-%m-%d)",
  "branch_hint": "$branch_hint",
  "notes": "Generated by decision-thread-preflight.sh --init"
}
EOF
  echo "✅ Manifest geschreven: $MANIFEST_FILE"
  echo "   Kopieer naar repo(s): cp $MANIFEST_FILE <repo>/.pagayo/decision-thread.json"
}

if [[ "$INIT_MODE" == "1" ]]; then
  init_manifest
  exit 0
fi

if [[ ! -d "$REPO_PATH/.git" ]]; then
  echo "❌ Geen git repo: $REPO_PATH"
  exit 1
fi

cd "$REPO_PATH"
REPO_NAME="$(basename "$(git rev-parse --show-toplevel)")"
BRANCH="$(git branch --show-current)"

# Diff scope: staged + unstaged tracked files
DIFF_FILES="$(git diff --name-only HEAD 2>/dev/null; git diff --name-only --cached 2>/dev/null)" || true
DIFF_FILES="$(printf '%s\n' "$DIFF_FILES" | sort -u | grep -v '^$' || true)"

if [[ -z "$DIFF_FILES" ]]; then
  echo "✅ Geen diff — decision-thread check overgeslagen"
  exit 0
fi

ADMIN_SIGNAL=0
REVENUE_SIGNAL=0

while IFS= read -r file; do
  [[ -z "$file" ]] && continue
  if [[ "$file" == *revenue-today* || "$file" == *REVENUE_TODAY* || "$file" == *revenue/today* ]]; then
    REVENUE_SIGNAL=1
  fi
  if [[ "$file" == *today/v1/* || "$file" == *today-v1* || "$file" == *TODAY_V1* \
     || "$file" == *capability* || "$file" == *admin-capability* \
     || "$file" == *CAPABILITY_* || "$file" == *tenant-capability* \
     || "$file" == *policy/capabilities* ]]; then
    ADMIN_SIGNAL=1
  fi
done <<<"$DIFF_FILES"

# Content scan for edge cases (renames)
if [[ "$ADMIN_SIGNAL" == "0" || "$REVENUE_SIGNAL" == "0" ]]; then
  DIFF_BODY="$(git diff HEAD 2>/dev/null; git diff --cached 2>/dev/null)" || true
  if [[ "$ADMIN_SIGNAL" == "0" ]] && echo "$DIFF_BODY" | grep -qE 'TODAY_V1|CAPABILITY_FIRST|today/v1|TenantCapability'; then
    ADMIN_SIGNAL=1
  fi
  if [[ "$REVENUE_SIGNAL" == "0" ]] && echo "$DIFF_BODY" | grep -qE 'REVENUE_TODAY|revenue-today|RevenueToday'; then
    REVENUE_SIGNAL=1
  fi
fi

MANIFEST_PATH=""
for candidate in ".pagayo/decision-thread.json" "$WS/.pagayo/decision-thread.json"; do
  if [[ -f "$candidate" ]]; then
    MANIFEST_PATH="$candidate"
    break
  fi
done

echo "🧵 Decision thread preflight — $REPO_NAME ($BRANCH)"

if [[ "$ADMIN_SIGNAL" == "1" && "$REVENUE_SIGNAL" == "1" ]]; then
  echo "❌ Cross-thread mix: diff raakt zowel admin/capability/Today v1 als Revenue Today."
  echo "   Split commits/PRs per slug (THREAD-ENFORCEMENT.md)."
  exit 1
fi

if [[ "$ADMIN_SIGNAL" == "0" && "$REVENUE_SIGNAL" == "0" ]]; then
  echo "✅ Geen thread-conflict signalen in diff"
  exit 0
fi

if [[ -z "$MANIFEST_PATH" ]]; then
  echo "⚠️  Thread-signalen in diff maar geen .pagayo/decision-thread.json — push mag, manifest aanbevolen."
  exit 0
fi

MANIFEST_SLUG="$(node -e "const m=require('$MANIFEST_PATH'); console.log(m.slug||'')" 2>/dev/null || true)"
MANIFEST_THREAD="$(node -e "const m=require('$MANIFEST_PATH'); console.log(m.thread_id||'')" 2>/dev/null || true)"
EXCLUDES_RAW="$(node -e "const m=require('$MANIFEST_PATH'); console.log((m.excludes||[]).join(','))" 2>/dev/null || true)"

if [[ -n "$MANIFEST_SLUG" ]] && [[ "$BRANCH" != *"$MANIFEST_SLUG"* ]] \
  && [[ "$BRANCH" != *"release-workflow"* ]] \
  && [[ "$BRANCH" != *"batch-staging"* ]]; then
  echo "❌ Branch '$BRANCH' bevat geen slug-hint '$MANIFEST_SLUG' uit manifest."
  exit 1
fi

if [[ -n "$EXCLUDES_RAW" ]]; then
  while IFS= read -r ex; do
    [[ -z "$ex" ]] && continue
    if echo "$DIFF_FILES" | grep -qi "$ex"; then
      echo "❌ Diff raakt uitgesloten thread: $ex"
      exit 1
    fi
  done <<<"$(echo "$EXCLUDES_RAW" | tr ',' '\n')"
fi

echo "✅ Thread OK — manifest $MANIFEST_THREAD / $MANIFEST_SLUG"
exit 0
